# Generated by Django 4.0.4 on 2022-05-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('stud_ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=12)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('department', models.CharField(choices=[('General', 'General'), ('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Information Systems', 'Information Systems'), ('Decision Support', 'Decision Support'), ('Artifical Intelligence', 'Artifical Intelligence')], max_length=25)),
                ('date', models.DateField()),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
